### ISSUE TITLE
Pie chart needs labels.

### ISSUE THREAD

**Issue by kfogel** [SolutionGuidance/psm-dashboard#29]
Right now you have to hover over the pie chart to see what each wedge means (or you have to flip your eyes back and forth between the pie chart and the color legend, which may be far away when the row-chart is in expanded mode, and in any case some people aren't good at remembering colors).  The wedges should just have labels too.

**Comment by PaulMorris** [comment]
Labels added.  (See commits b68709efed9d82ca76f8bcce5a1078b57256a633 , 4297d21afc4cb8bb3a944e22553de160f9968ca9 , and 758e178541eb1bde346201139a27fbd5cdbbf1e9.)
