### ISSUE TITLE
Describe the feature burn-down chart.

### ISSUE THREAD

**Issue by kfogel** [SolutionGuidance/psm-dashboard#30]
Let's put a caption above the feature burn-down chart, say, "Progress to completion, by feature -- click on a row for details:" (unless you think of something better, which would be fine).

**Comment by kfogel** [comment]
This becomes more important in light of issue #32.

**Comment by PaulMorris** [comment]
Resolved by commit 0fa7a6d13c28aed7330906daf74845880ef613bf , closing.
