### ISSUE TITLE
Get rid of "Show Feature Descriptions" checkbox entirely.

### ISSUE THREAD

**Issue by kfogel** [SolutionGuidance/psm-dashboard#32]
We can get rid of the "Show Feature Descriptions" checkbox, as per [Zulip chat](https://chat.opentechstrategies.com/#narrow/stream/6-Provider-Screening/subject/dashboard/near/52184).  We only want the expanded view -- it's the only view that matters to the audience the dashboard is now addressing.

**Comment by PaulMorris** [comment]
Resolved by commit 5b7befda01ac7ed69550ee127ff63fcff890fa75 , closing.
