### ISSUE TITLE
Burn-down chart per-row tooltip popup should show "size" of row (number of reqs associated).

### ISSUE THREAD

**Issue by kfogel** [SolutionGuidance/psm-dashboard#36]
The per-row tooltip that pops up when you hover over a row in the burndown chart should show a count of the individual PSM reqs associated with that row's high-level feature (and maybe a count of the associated issues too).

E.g., a new line at the bottom of the tooltip window, saying "**5** sub-requirements (**18** issues)" or whatever.

**Comment by kfogel** [comment]
@PaulMorris [tentatively estimated](https://chat.opentechstrategies.com/#narrow/stream/6-Provider-Screening/subject/Checkins/near/53828) 3-6 hours, most likely on the shorter end of that, to implement this.  We won't hold him to that if there turn out to be unexpected complications :-), but let's plan with that estimate in mind.

**Comment by PaulMorris** [comment]
It only took about 45 minutes.  Implemented in commits [555a2724287a078bb632af09da1c9a2d5a233a9c](https://github.com/SolutionGuidance/psm/commit/555a2724287a078bb632af09da1c9a2d5a233a9c) and [87679106617a6c03cd0c58a4a1a11368b7a7b532](https://github.com/SolutionGuidance/psm/commit/87679106617a6c03cd0c58a4a1a11368b7a7b532) in the gh-pages branch of the main psm repo.
