### ISSUE TITLE
Burn-down chart: Extend green "Completed" bars all the way to the today line.

### ISSUE THREAD

**Issue by kfogel** [SolutionGuidance/psm-dashboard#37]
'Nuff said.

(For reference: the [Zulip chat conversation](https://chat.opentechstrategies.com/#narrow/stream/6-Provider-Screening/subject/dashboard/near/52439) where we decided this.)

**Comment by PaulMorris** [comment]
Implemented in commit [ba65aa12fa9d33e4d801dc158fe5c3ef0fb70a05](https://github.com/SolutionGuidance/psm/commit/ba65aa12fa9d33e4d801dc158fe5c3ef0fb70a05) on the gh-pages branch in the main psm repo.
