### ISSUE TITLE
Burn-down chart: change "ongoing" feature color from purple to a shade of green.

### ISSUE THREAD

**Issue by kfogel** [SolutionGuidance/psm-dashboard#38]
We should visually reflect the fact that "ongoing" features are more similar to completed items than they are to not-started or in-progress items (because with "ongoing", we do a more-or-less set and predictable amount of that task in any given time period, and as long as we do that amount, the task is as completed as it can be with respect to that time period).

So let's switch "ongoing" to green.  The only question is, should it be a lighter or a darker shade of green than the "completed" color?  My instinct says slightly darker, but I'm not actually looking at side-by-side samples right now, so I leave that to the implementor's judgement.

**Comment by PaulMorris** [comment]
Done in commit [620888e0add05134f0c43749fe3772f636267355](https://github.com/SolutionGuidance/psm/commit/620888e0add05134f0c43749fe3772f636267355) on the gh-pages branch of the main PSM app.

Before:

![screenshot_2018-09-07 dashboard 1](https://user-images.githubusercontent.com/1091693/45249779-45589e00-b2f4-11e8-8eae-38b9a1c88081.png)

![screenshot_2018-09-07 dashboard 3](https://user-images.githubusercontent.com/1091693/45249809-fbbc8300-b2f4-11e8-8a47-856e26e6ef90.png)

After:

![screenshot_2018-09-07 dashboard](https://user-images.githubusercontent.com/1091693/45249780-45589e00-b2f4-11e8-8c0f-5656d44a1ea3.png)

![screenshot_2018-09-07 dashboard 2](https://user-images.githubusercontent.com/1091693/45249810-fbbc8300-b2f4-11e8-93a9-dc29b6aabdad.png)
