### ISSUE TITLE
The "get-inputs" script needs to be updated for new columns in the spreadsheet.

### ISSUE THREAD

**Issue by kfogel** [SolutionGuidance/psm-dashboard#4]
We added three new columns to the [PSM Features - RTM Map](https://docs.google.com/spreadsheets/d/1avMeCIiayaCcx8fDzldo3KEiRHyM2qjjBuCXWKRwyao/edit#gid=0) spreadsheet today:

* **C** User-visibility
* **D** Tech Dependencies
* **E** Effort level

The `get-inputs` script needs to be updated accordingly.

**Comment by kfogel** [comment]
There might have been more columns, or at least one more column, added since the above, by the way.

**Comment by cecilia-donnelly** [comment]
Resolved in 3262e3f4 and c7fc6c1d9.
