### ISSUE TITLE
Burn-down chart: Show subfeatures list (if any) in tooltip popup.

### ISSUE THREAD

**Issue by kfogel** [SolutionGuidance/psm-dashboard#40]
In `features-info.json` (on the `gh-pages` branch of the main PSM repository), some of the high-level feature have a non-empty `subFeatures` list.  For example:

        "psm-feature-040": {
            "feature_id": "psm-feature-040",
            "description": "Add new fields for specific requirements relating to bordering-state providers, care settings, help, etc.",
            "subfeatures": [
                "Detect bordering-state providers",
                "Ask specific questions of bordering-state providers",
                "Make state borders and border regions configurable",
                "Screen provider location for in-state or bordering-state",
                "Limit state Medicaid IDs to not conflict with NPIs",
                "Research \"care settings\" in various states",
                "Add care settings UI",
                "Add start/end dates for provider data"
            ],
    
          ...}

When sub-features are present, we should show them in the tooltip popup.  At least, that's what I propose -- see [discussion started in Zulip chat](https://chat.opentechstrategies.com/#narrow/stream/6-Provider-Screening/subject/dashboard/near/55271) for followup.

**Comment by PaulMorris** [comment]
Done via commits:
https://github.com/SolutionGuidance/psm/commit/2b72131b62a873401a42cfa05ce84b06fe0527cc
https://github.com/SolutionGuidance/psm/commit/1a96f1d395817b3015692d91af6726aa49d9ed45

See further zulip conversation here:
https://chat.opentechstrategies.com/#narrow/stream/6-Provider-Screening/subject/dashboard/near/55333
