### ISSUE TITLE
Mark ongoing features

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm-dashboard#6]
Mark certain features, like documentation, "ongoing" to differentiate them from features that are in progress but will eventually come to an end (like reports). Ongoing features wouldn't include a percentage done.  They'll be in a 4th color and excluded from the pie chart.  They should sit at the bottom of the burndown chart.  The purpose of including them is to show that effort will continue to be spent on them, even though they won't "end" until the project reaches 1.0 (and frequently not even then).

**Comment by cecilia-donnelly** [comment]
Note that these features are already marked "Ongoing" in the Status column of the source spreadsheet.

**Comment by PaulMorris** [comment]
Closed via PR #34.
