### ISSUE TITLE
Show dashboard on projectpsm homepage

### ISSUE THREAD

**Issue by cecilia-donnelly** [SolutionGuidance/psm-dashboard#7]
Show the dashboard at http://projectpsm.org/dashboard.  This includes adding the regular PSM logo, header menu, etc, and generally formatting it to match the layout of that site.  Push the charts more toward the center of the page to match the margins.  Add link to dashboard from projectpsm.org main page.  

Note that for the dashboard to show up there it will need to be pushed to the gh-pages branch of the main PSM repo (at least as long as projectpsm.org is a GitHub Pages site).

**Comment by cecilia-donnelly** [comment]
Note that @pjsier suggested we put the dashboard into an iframe in the GitHub Pages for this repo, so that it can be pulled into projectpsm.org without making changes to the PSM repo itself.

**Comment by kfogel** [comment]
This is done -- closing.
